import os
import json
import xml.sax.saxutils as saxutils
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from config import Config

def safe_text(text):
    """Escapes XML entities so ReportLab Paragraph does not fail on &, <, >."""
    if text is None:
        return ""
    return saxutils.escape(str(text))

def generate_pdf_report(analysis_report, user_name="User"):
    """
    Generates a professional PDF Incident Report using ReportLab.
    Handles both sqlite3.Row and dict objects safely.
    Returns absolute path to generated PDF.
    """
    if hasattr(analysis_report, 'keys'):
        analysis_report = dict(analysis_report)
    elif not isinstance(analysis_report, dict):
        analysis_report = dict(analysis_report)

    report_id = analysis_report.get('id', 0)
    created_at = analysis_report.get('created_at', str(datetime.now())[:19])
    
    # Meaningful file name with report id
    filename = f"ScamShield_Incident_Report_{report_id}.pdf"
    file_path = os.path.join(Config.REPORTS_FOLDER, filename)
    
    doc = SimpleDocTemplate(
        file_path,
        pagesize=letter,
        rightMargin=40, leftMargin=40,
        topMargin=36, bottomMargin=36
    )
    
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=18,
        textColor=colors.HexColor('#0284c7'),
        spaceAfter=3
    )
    
    subtitle_style = ParagraphStyle(
        'DocSubTitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        textColor=colors.HexColor('#64748b'),
        spaceAfter=12
    )
    
    section_heading = ParagraphStyle(
        'SectionHeading',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=12,
        textColor=colors.HexColor('#0f172a'),
        spaceBefore=10,
        spaceAfter=5
    )
    
    body_style = ParagraphStyle(
        'BodyTextCustom',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9.5,
        leading=13.5,
        textColor=colors.HexColor('#1e293b')
    )
    
    disclaimer_style = ParagraphStyle(
        'DisclaimerText',
        parent=styles['Normal'],
        fontName='Helvetica-Oblique',
        fontSize=8.5,
        leading=11.5,
        textColor=colors.HexColor('#92400e')
    )

    story = []
    
    # 1. Header Banner
    story.append(Paragraph("SCAMSHIELD AI — DIGITAL FRAUD & THREAT INCIDENT REPORT", title_style))
    story.append(Paragraph(f"Generated by ScamShield AI Platform | Date & Time: {safe_text(created_at)}", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor('#0284c7'), spaceAfter=12))
    
    # Parse fields safely
    risk_level = str(analysis_report.get('risk_level', 'SUSPICIOUS')).upper()
    scam_type = analysis_report.get('scam_type', 'General Suspicious Communication')
    message_text = analysis_report.get('message_text', '')
    language = analysis_report.get('language', 'en')
    
    try:
        raw_ind = analysis_report.get('indicators_json', '[]')
        indicators = json.loads(raw_ind) if isinstance(raw_ind, str) else raw_ind
    except Exception:
        indicators = [str(raw_ind)]
        
    try:
        raw_urls = analysis_report.get('urls_json', '[]')
        urls = json.loads(raw_urls) if isinstance(raw_urls, str) else raw_urls
    except Exception:
        urls = []
        
    try:
        raw_sug = analysis_report.get('safety_suggestions_json', '[]')
        suggestions = json.loads(raw_sug) if isinstance(raw_sug, str) else raw_sug
    except Exception:
        suggestions = [str(raw_sug)]

    try:
        raw_steps = analysis_report.get('next_steps_json', '[]')
        next_steps_list = json.loads(raw_steps) if isinstance(raw_steps, str) else raw_steps
    except Exception:
        next_steps_list = []

    # Extract AI summary / explanation from full_json
    summary = ""
    what_we_detect = []
    try:
        raw_full = analysis_report.get('full_json', '{}')
        full = json.loads(raw_full) if isinstance(raw_full, str) else raw_full
        if isinstance(full, dict):
            summary = full.get('summary', '')
            if not next_steps_list:
                next_steps_list = full.get('next_steps', [])
            if not suggestions:
                suggestions = full.get('safety_suggestions', [])
            
            # Detect flags
            if full.get('urgency_detected'):
                what_we_detect.append("Urgency / Pressure Tactics: Demands prompt compliance or threatens punitive action.")
            if full.get('payment_request_detected'):
                what_we_detect.append("Payment Demands: Upfront fees, processing charges, or direct UPI transfer requests.")
            if full.get('credential_request_detected'):
                what_we_detect.append("Credential Phishing: Solicits sensitive OTPs, passwords, PINs, or net banking information.")
    except Exception:
        pass

    if not summary:
        summary = (
            f"The analyzed communication exhibits patterns consistent with {scam_type}. "
            f"Evaluated risk level is classified as {risk_level} based on natural language heuristic cues "
            f"and threat indicators."
        )

    if not what_we_detect:
        if risk_level == 'HIGH':
            what_we_detect = [
                "Urgent deadline or fear/pressure tactics to bypass critical thinking.",
                "Requests for upfront money, processing fees, or confidential banking/OTP credentials.",
                "Impersonation of trusted institutions, government bodies, or financial authorities."
            ]
        elif risk_level == 'SUSPICIOUS':
            what_we_detect = [
                "Unverified sender communication containing suspicious phrasing or links.",
                "Call to action requiring verification, account reactivation, or link interaction."
            ]
        else:
            what_we_detect = [
                "Standard communicative pattern without recognized coercive or phishing markers.",
                "No explicit requests for credentials or monetary transfers detected."
            ]

    if not suggestions:
        suggestions = [
            "Never share OTPs, PINs, CVVs, or net banking passwords under any circumstance.",
            "Verify the caller or sender identity through officially published customer service channels.",
            "Do not transfer money or pay processing fees to claim prizes or job offers."
        ]

    if not next_steps_list:
        next_steps_list = [
            "Do not click on links or reply to the suspicious message.",
            "Block and report the sender on your communication platform.",
            "Report fraudulent incidents on the National Cybercrime Portal at cybercrime.gov.in or call 1930."
        ]

    # Color code risk badge
    if risk_level == 'HIGH':
        badge_bg = colors.HexColor('#fee2e2')
        badge_text_color = '#dc2626'
        risk_label = "HIGH RISK — FRAUD / SCAM DETECTED"
    elif risk_level == 'SUSPICIOUS':
        badge_bg = colors.HexColor('#fef3c7')
        badge_text_color = '#d97706'
        risk_label = "SUSPICIOUS — PROCEED WITH CAUTION"
    else:
        badge_bg = colors.HexColor('#dcfce7')
        badge_text_color = '#16a34a'
        risk_label = "LOW RISK — APPEARS LEGITIMATE"

    # Metadata Table
    meta_data = [
        [
            Paragraph("<b>Incident Report ID:</b>", body_style),
            Paragraph(f"#{report_id:05d}", body_style),
            Paragraph("<b>Analyzed User:</b>", body_style),
            Paragraph(safe_text(user_name), body_style)
        ],
        [
            Paragraph("<b>Analysis Date:</b>", body_style),
            Paragraph(safe_text(created_at), body_style),
            Paragraph("<b>Language:</b>", body_style),
            Paragraph(safe_text(str(language).upper()), body_style)
        ],
        [
            Paragraph("<b>Scam Category:</b>", body_style),
            Paragraph(f"<b>{safe_text(scam_type)}</b>", body_style),
            Paragraph("<b>Assigned Risk:</b>", body_style),
            Paragraph(f"<b><font color='{badge_text_color}'>{risk_label}</font></b>", body_style)
        ]
    ]
    
    meta_table = Table(meta_data, colWidths=[120, 150, 110, 150])
    meta_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f8fafc')),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#cbd5e1')),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
        ('PADDING', (0,0), (-1,-1), 5),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 10))

    # 2. Analyzed Communication Message
    story.append(Paragraph("1. Submitted Communication Message", section_heading))
    msg_box = Table([[Paragraph(f"<i>\"{safe_text(message_text)}\"</i>", body_style)]], colWidths=[530])
    msg_box.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f1f5f9')),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#cbd5e1')),
        ('PADDING', (0,0), (-1,-1), 7),
    ]))
    story.append(msg_box)
    story.append(Spacer(1, 10))

    # 3. AI Risk Prediction & Explanation
    story.append(Paragraph("2. AI Risk Prediction & Detailed Explanation", section_heading))
    exp_box = Table([[Paragraph(safe_text(summary), body_style)]], colWidths=[530])
    exp_box.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#e0f2fe')),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#7dd3fc')),
        ('PADDING', (0,0), (-1,-1), 7),
    ]))
    story.append(exp_box)
    story.append(Spacer(1, 10))

    # 4. What We Detect
    story.append(Paragraph("3. What We Detect (Threat Pattern Analysis)", section_heading))
    for item in what_we_detect:
        story.append(Paragraph(f"• <b>{safe_text(item)}</b>", body_style))
    story.append(Spacer(1, 10))

    # 5. Suspicious Indicators Detected
    story.append(Paragraph("4. Suspicious Indicators Detected", section_heading))
    if indicators:
        for ind in indicators:
            story.append(Paragraph(f"• {safe_text(ind)}", body_style))
    else:
        story.append(Paragraph("• No specific red flags detected in communication.", body_style))
    story.append(Spacer(1, 10))

    # 6. URL & Link Safety Analysis
    story.append(Paragraph("5. URL & Link Safety Analysis", section_heading))
    if urls:
        for item in urls:
            if isinstance(item, dict):
                u_str = item.get('url', 'N/A')
                obs_list = item.get('observations', [])
            else:
                u_str = str(item)
                obs_list = []
            story.append(Paragraph(f"<b>Detected URL:</b> {safe_text(u_str)}", body_style))
            for obs in obs_list:
                story.append(Paragraph(f"   - {safe_text(obs)}", body_style))
    else:
        story.append(Paragraph("No external web links detected in the message.", body_style))
    story.append(Spacer(1, 10))

    # 7. Safety Recommendations
    story.append(Paragraph("6. Safety Recommendations", section_heading))
    for sug in suggestions:
        story.append(Paragraph(f"✔ {safe_text(sug)}", body_style))
    story.append(Spacer(1, 10))

    # 8. Immediate Next Steps
    story.append(Paragraph("7. Immediate Actionable Next Steps", section_heading))
    for idx, step in enumerate(next_steps_list, 1):
        story.append(Paragraph(f"<b>Step {idx}:</b> {safe_text(step)}", body_style))
    story.append(Spacer(1, 14))

    # 9. Disclaimer
    disclaimer_text = (
        "<b>OFFICIAL NOTICE & LEGAL DISCLAIMER:</b> "
        "This report is an automated risk assessment generated by ScamShield AI for informational purposes. "
        "It does not constitute definitive legal or factual determination of fraud. "
        "If you suspect financial fraud, immediately report the incident to your bank, call National Cyber Helpline <b>1930</b>, "
        "or file an official report at <b>cybercrime.gov.in</b>."
    )
    disc_box = Table([[Paragraph(disclaimer_text, disclaimer_style)]], colWidths=[530])
    disc_box.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#fef3c7')),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#fde68a')),
        ('PADDING', (0,0), (-1,-1), 7),
    ]))
    story.append(disc_box)
    
    # Build document
    doc.build(story)
    return file_path
